config/routes.rb
Rails.application.routes.draw do
  get "sessions/new", as: "login"
  get "sessions/create"
  get "sessions/destroy", as: "logout"
  root "games#index"

  resources :sessions
  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics

    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  resources :users

  # Routes for Codeable Design
  get "/design", to: "design#index"
  get "/design/sections", to: "design#sections"
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  # Validations
  # Default value 'false' has been set on database migration for developer and publisher
  # Rails will convert the string values "false" or "0" from the form to the boolean 'false'
  #   and any other string value to the boolean 'true'
  #   with the exception of the empty string "" that is converted to nil

  validates :company, uniqueness: { scope: :game, message: "and Game combination already taken" }
  validates :developer, presence: { message: "and Publisher can't be blank" },
                        unless: proc { publisher? }
  validates :publisher, presence: { message: "and Developer can't be blank" },
                        unless: proc { developer? }

  # Associations
  belongs_to :game
  belongs_to :company
end

app/controllers/involved_companies_controller.rb
class InvolvedCompaniesController < ApplicationController
  # GET /involved_companies
  def index
    @involved_companies = InvolvedCompany.all
  end

  # GET /involved_companies/:id
  def show
    @involved_company = InvolvedCompany.find(params[:id])
  end

  # GET /involved_companies/new
  def new
    @involved_company = InvolvedCompany.new
  end

  # GET /involved_companies/:id/edit
  def edit
    @involved_company = InvolvedCompany.find(params[:id])
  end

  # POST /involved_companies
  def create
    @involved_company = InvolvedCompany.new(involved_company_params)

    if @involved_company.save
      redirect_to @involved_company
    else
      render :new
    end
  end

  # PATCH/PUT /involved_companies/:id
  def update
    @involved_company = InvolvedCompany.find(params[:id])

    if @involved_company.update(involved_company_params)
      redirect_to @involved_company
    else
      render :edit
    end
  end

  # DELETE /involved_companies/:id
  def destroy
    @involved_company = InvolvedCompany.find(params[:id])
    @involved_company.destroy
    redirect_to involved_companies_url
  end

  private

  # Only allow a list of trusted parameters through.
  def involved_company_params
    params.require(:involved_company).permit(:game_id, :company_id, :developer, :publisher)
  end
end

app/helpers/involved_companies_helper.rb
module InvolvedCompaniesHelper
end

app/views/involved_companies/_form.html.erb
<%= form_with(model: involved_company, class: "generic-container") do |form| %>
  <div class="flex gap-16 mb-8">
    <div class="select">
      <%= form.label :game_id, class:"content--xs overline"%>
      <%= form.collection_select :game_id, Game.all, :id, :name, { prompt: true }, { class: "select__input" } %>
      <% if involved_company.errors.messages[:game].any? %>
      <span class="content--sm input__error-message">
        <%= involved_company.errors.messages[:game].join(", ")%>
      </span>
      <% end %>
    </div>
  </div>

  <div class="flex gap-16 mb-8">
    <div class="select">
      <%= form.label :company_id, class:"content--xs overline"%>
      <%= form.collection_select :company_id, Company.all, :id, :name, { prompt: true }, { class: "select__input" } %>
      <% if involved_company.errors.messages[:company].any? %>
      <span class="content--sm input__error-message">
        <%= involved_company.errors.messages[:company].join(", ")%>
      </span>
      <% end %>
    </div>
  </div>

  <div>
    <p class="mb-4">Involvement:</p>
    <div class="checkbox__opt-group">
      <div class="checkbox">
        <%= form.check_box :developer, class: "checkbox__input" %>
        <div class="checkbox__text-container">
          <%= form.label :developer, class:"content--sm"%>
          <% if involved_company.errors.messages[:developer].any? %>
            <span class="content--sm input__error-message">
              <%= involved_company.errors.messages[:developer].join(", ")%>
            </span>
          <% end %>
        </div>
      </div>
      <div class="checkbox">
        <%= form.check_box :publisher, class: "checkbox__input" %>
        <div class="checkbox__text-container">
          <%= form.label :publisher, class:"content--sm"%>
          <% if involved_company.errors.messages[:publisher].any? %>
            <span class="content--sm input__error-message">
              <%= involved_company.errors.messages[:publisher].join(", ")%>
            </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= form.submit class: "btn btn--primary btn--fit-content" %>

<% end %>

app/views/involved_companies/edit.html.erb
<section class="section--sm">
  <div class="container">
    <h1 class="heading">Editing Involved Company</h1>

    <%= render 'form', involved_company: @involved_company %>

    <%= link_to 'Back', involved_companies_path %>
  </div>
</section>

app/views/involved_companies/index.html.erb
<section class="section--sm">
  <div class="container">
    <h1 class="heading">Involved Companies</h1>

    <div class="table-container">
    <table>
      <thead>
        <tr>
          <th scope="col">Game</th>
          <th scope="col">Company</th>
          <th scope="col">Developer</th>
          <th scope="col">Publisher</th>
          <th scope="colgroup" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @involved_companies.each do |involved_company| %>
          <tr>
            <td><%= involved_company.game.name %></td>
            <td><%= involved_company.company.name %></td>
            <td><%= involved_company.developer %></td>
            <td><%= involved_company.publisher %></td>
            <td><%= link_to 'Show', involved_company %></td>
            <td><%= link_to 'Edit', edit_involved_company_path(involved_company) %></td>
            <td><%= link_to 'Destroy', involved_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>

    <br>

    <%= link_to 'New involved_company', new_involved_company_path, class: "btn btn--primary btn--fit-content" %>
  </div>
</section>

app/views/involved_companies/new.html.erb
<section class="section--sm">
  <div class="container">
    <h1 class="heading">New Involved Company</h1>

    <%= render 'form', involved_company: @involved_company %>

    <%= link_to 'Back', involved_companies_path %>
  </div>
</section>

app/views/involved_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @involved_company.game_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @involved_company.company_id %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @involved_company.developer %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @involved_company.publisher %>
</p>

<%= link_to 'Edit', edit_involved_company_path(@involved_company) %> |
<%= link_to 'Back', involved_companies_path %>