config/routes.rb
Rails.application.routes.draw do
  get "sessions/new", as: "login"
  get "sessions/create"
  get "sessions/destroy", as: "logout"
  root "games#index"

  resources :sessions
  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics

    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  resources :users

  # Routes for Codeable Design
  get "/design", to: "design#index"
  get "/design/sections", to: "design#sections"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="shadow">
      <div class="navbar">
        <div class="navbar__left">
          <a href="/" class="navbar__logo">
            <img src="/images/logo.png" />
          </a>
          <ul class="navbar__item-list">
            <li class="navbar__item">
              <%= link_to 'Users', users_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Companies', companies_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Genres', genres_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Platforms', platforms_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Games', games_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Involved Companies', involved_companies_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Critics', critics_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Create an account',new_user_path, class: "navbar__link" %>
            </li>
            <li class="navbar__item">
              <%= link_to 'Login',  class: "navbar__link" %>
            </li>
             <% if current_user %>
                Logged in as <%= current_user.email %>
                <%= link_to "Log Out", logout_path %>
              <% else %>
                <%= link_to "Log In", login_path %>
              <% end %>
          </ul>
          
        </div>
        <div class="navbar__right align-center">
        </div>
      </div>
    </div>
  
  <%= yield %>
  </body>
</html>